"Hello world sample, please remove"
type HelloWorldAcssChannelAfccReload{
  "text"
  sn: String!  
}

"Actor types"
enum AcssChannelAfccReloadActorType{
  FARECOLLECTOR
  RELOADNETWORK
  PARTIES
}

type AcssChannelAfccReloadEventBusinessUnit{
  "Business unit id"
  id: String
  "Business unit name"
  name: String
}

"AFCC data object"
type AcssChannelAfccReloadEventAfcc{
  "Payment method before reload"
  before: String
  "Payment method after reload"
  after: String
  "MISSING"
  UId: String
  "Payment method Id"
  cardId: String
  "Payment method balance before reload"
  balanceBefore: Int
  "Payment method balance after reload"
  balanceAfter: Int
}

type AcssChannelAfccReloadSource{
  "Maquine where reload was made"
  machine: String
  "Machine IP where the transaction was made"
  ip: String
}

"Reprents an AFCC reload event"
type AcssChannelAfccReloadEvent {
  "Event Id"
  id: ID
  "Reload amount"
  amount: Int
  "Business unit id"
  bu: AcssChannelAfccReloadEventBusinessUnit
  "AFCC data object"
  afcc: AcssChannelAfccReloadEventAfcc
  "Event source"
  source: AcssChannelAfccReloadSource

}

type AcssChannelAfccReloadChannel{
  "Channel processor id"
  id: String
  "Channel softwate version"
  sv: String
  "Channel configuration version"
  conf: BigInt
}

type AcssChannelAfccReloadEvt{
  "Source event id"
  id: String
  "source event type"
  type: String
  "source event responsible user"
  user: String
}

"Represent transaction that are created by the microservice after process an AFCC reload event"
type AcssChannelAfccReloadTransaction{
  "Transaction timestamp"
  timestamp: BigInt
  "Consignee business unit id"
  fromBuId: String
  "Beneficiary business unit id"
  toBuId: String
  "Money amount"
  amount: Int
  "Transaction's channel processor"
  channel: AcssChannelAfccReloadChannel
  "Transaction Type"
  type: String
  "Source event"
  evt: AcssChannelAfccReloadEvt
}


type AcssChannelAfccReloadActor{
  "Actor's business unit Id"
  buId: String
  "Actor name"
  name: String
  "percentage belonging"
  percentage: Float
}

input AcssChannelAfccReloadActorInput{
  "Actor's business unit Id"
  buId: String
  "Actor name"
  name: String
  "percentage belonging"
  percentage: Float
}

"Object that represent the rules to create transactions from AFCC event"
type AcssChannelAfccReloadConfigurationObject{
  "configuration id"
  id: BigInt 
  "List of Farecollector actors in this configuration"
  fareCollectors: [AcssChannelAfccReloadActor]
  "List of reloadNetwork Actors in this configuration"
  reloadNetworks: [AcssChannelAfccReloadActor]
  "List of parties actors in this configuration"
  parties: [AcssChannelAfccReloadActor]
  "Last edition for this configuation"
  lastEdition: BigInt
  "user who Created this configuration"
  editor: String
}

"Object that represent the rules to create transactions from AFCC event"
input AcssChannelAfccReloadConfigurationInput{
  "configuration id"
  id: BigInt 
  "List of Farecollector actors in this configuration"
  fareCollectors: [AcssChannelAfccReloadActorInput]
  "List of reloadNetwork Actors in this configuration"
  reloadNetworks: [AcssChannelAfccReloadActorInput]
  "List of parties actors in this configuration"
  parties: [AcssChannelAfccReloadActorInput]
  "Last edition for this configuation"
  lastEdition: BigInt
}

type AcssChannelAfccReloadCommandResponse{
  "Response code"
  code: Int
  "Response message"
  message: String
}

type Query {
  AcssChannelAfccReloadGetConfiguration(id: BigInt!): AcssChannelAfccReloadConfigurationObject
  AcssChannelAfccReloadGetAfccReloads(page: Int!, count: Int!, lowerLimit: BigInt, sortColumn: String, sortOrder: String): [AcssChannelAfccReloadEvent]
  AcssChannelAfccReloadGetAfccReload(id: ID!): AcssChannelAfccReloadEvent
  # AcssChannelAfccReloadGetAfccReloadDetails: AcssChannelAfccReloadEventDetail
  AcssChannelAfccReloadGetTransactionsFromAfccEvt(evtId: ID!): [AcssChannelAfccReloadTransaction]
  AcssChannelAfccReloadGetTransactions(page: Int!, count: Int!, sortColumn: String, sortOrder: String): [AcssChannelAfccReloadTransaction]
  AcssChannelAfccReloadGetReloadsCount: Int!

}

type Subscription {
  "Hello world sample, please remove"
  AcssChannelAfccReloadHelloWorldSubscription: HelloWorldAcssChannelAfccReload
}

type Mutation {
  AcssChannelAfccReloadCreateConfiguration(input: AcssChannelAfccReloadConfigurationInput!): AcssChannelAfccReloadCommandResponse
} 